{
 "title": "Accidents severity predictions",
 "time": { "from": "2016-07-01T23:00:00.000Z", "to": "2018-07-03T23:00:00.000Z" },
 "panels": [
  {
   "title": "Total accidents per day",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date AS \"time\", COUNT(\"accident.accident_index\") AS \"value\" FROM recent_accidents_dataset GROUP BY date "
    }
   ]
  },
  {
   "title": "Latest Accidents locations",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"accident.latitude\", \"accident.longitude\" FROM recent_accidents_dataset ORDER BY date DESC LIMIT 5000 "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT date AS \"time\", prediction_drift FROM recent_evidently_report "
    }
   ]
  },
  {
   "title": "Number of drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT date AS \"time\", num_drifted_columns FROM recent_evidently_report "
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT date AS \"time\", share_missing_values FROM recent_evidently_report "
    }
   ]
  }
 ]
}